#!/usr/bin/env sh
#
# Gradle wrapper script (Unix).
# This file is normally generated by `gradle wrapper` / Android Studio.
#
# It is included here so the project can be built from the command line:
#   ./gradlew assembleDebug
#

DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
JAVA_EXEC="${JAVA_HOME:+$JAVA_HOME/bin/}java"

if [ ! -x "$JAVA_EXEC" ]; then
  JAVA_EXEC="java"
fi

exec "$JAVA_EXEC" -jar "$DIR/gradle/wrapper/gradle-wrapper.jar" "$@"

